# Auto-generated by scripts/generate_pb2.py
"""Compatibility wrapper for arenaagent.generated.arena.message.startup_msg_pb2."""

import importlib
import sys

_module = importlib.import_module("arenaagent.generated.arena.message.startup_msg_pb2")
sys.modules[__name__] = _module
