#!/usr/bin/env python
import os
import re
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
PROTO_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "protocol"))
PROTO_INCLUDE_ARENA = os.path.join(PROTO_DIR, "arena")
PROTO_INCLUDE_TONGTONG = os.path.join(PROTO_DIR, "tongtong")
ARENA_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "arenaagent", "generated"))
OUTPUT_DIR = os.path.abspath(
    os.path.join(
        SCRIPT_DIR, "..", "arenaagent", "generated"
    )
)

BLACKLIST_DIRS = [""]
GENERATED_IMPORT_PREFIX = "arenaagent.generated"
COMPAT_PACKAGE_ROOTS = ("arena", "launcher")
COMPAT_FILE_HEADER = "# Auto-generated by scripts/generate_pb2.py\n"


def is_blacklisted(path: str) -> bool:
    relative = os.path.relpath(path, PROTO_DIR)
    return any(relative.split(os.sep)[0] == b for b in BLACKLIST_DIRS)


def _is_under_output(path: str) -> bool:
    try:
        return os.path.commonpath([OUTPUT_DIR, path]) == OUTPUT_DIR
    except ValueError:
        return False


def _is_under(path: str, root: str) -> bool:
    try:
        return os.path.commonpath([path, root]) == root
    except ValueError:
        return False


def ensure_arena_package() -> None:
    os.makedirs(ARENA_DIR, exist_ok=True)
    init_path = os.path.join(ARENA_DIR, "__init__.py")
    if not os.path.exists(init_path):
        with open(init_path, "w") as f:
            f.write("# Auto-generated\n")


def find_proto_files():
    for root, _, files in os.walk(PROTO_DIR):
        if is_blacklisted(root):
            continue
        for f in files:
            if f.endswith(".proto"):
                yield os.path.join(root, f)


def ensure_init_packages(relevant_path: str):
    """Ensure all intermediate folders have __init__.py"""
    pkg_dir = os.path.dirname(relevant_path)
    while pkg_dir and _is_under_output(pkg_dir):
        init_path = os.path.join(pkg_dir, "__init__.py")
        if not os.path.exists(init_path):
            with open(init_path, "w") as f:
                f.write("# Auto-generated\n")
        parent = os.path.dirname(pkg_dir)
        if parent == pkg_dir:
            break
        pkg_dir = parent


def _is_generated_compat_file(path: str) -> bool:
    if not os.path.exists(path):
        return True

    with open(path, encoding="utf-8") as f:
        return f.read(len(COMPAT_FILE_HEADER)) == COMPAT_FILE_HEADER


def _write_compat_file(path: str, content: str) -> None:
    if not _is_generated_compat_file(path):
        raise RuntimeError(f"Refusing to overwrite non-generated compatibility file: {path}")

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def _package_init_content(package_name: str) -> str:
    return (
        COMPAT_FILE_HEADER
        + f'"""Compatibility package for generated protobuf imports under {package_name}."""\n'
    )


def _module_wrapper_content(generated_module: str) -> str:
    return (
        COMPAT_FILE_HEADER
        + f'"""Compatibility wrapper for {generated_module}."""\n\n'
        + "import importlib\n"
        + "import sys\n\n"
        + f'_module = importlib.import_module("{generated_module}")\n'
        + "sys.modules[__name__] = _module\n"
    )


def _stub_wrapper_content(generated_module: str) -> str:
    return COMPAT_FILE_HEADER + f"from {generated_module} import *\n"


def _module_name_from_relative_path(relative_path: str) -> str:
    return os.path.splitext(relative_path)[0].replace(os.sep, ".")


def generate_compat_package(package_root: str) -> None:
    generated_root = os.path.join(OUTPUT_DIR, package_root)
    if not os.path.isdir(generated_root):
        return

    for root, dirs, files in os.walk(generated_root):
        dirs[:] = [d for d in dirs if d != "__pycache__"]

        package_relative_dir = os.path.relpath(root, OUTPUT_DIR)
        package_name = package_relative_dir.replace(os.sep, ".")
        compat_dir = os.path.join(REPO_ROOT, package_relative_dir)
        _write_compat_file(
            os.path.join(compat_dir, "__init__.py"),
            _package_init_content(package_name),
        )

        for file_name in files:
            if file_name == "__init__.py" or file_name.endswith(".pyc"):
                continue

            generated_path = os.path.join(root, file_name)
            relative_path = os.path.relpath(generated_path, OUTPUT_DIR)
            compat_path = os.path.join(REPO_ROOT, relative_path)

            if file_name.endswith(".py"):
                generated_module = f"{GENERATED_IMPORT_PREFIX}.{_module_name_from_relative_path(relative_path)}"
                _write_compat_file(compat_path, _module_wrapper_content(generated_module))
            elif file_name.endswith(".pyi"):
                module_relative_path = os.path.splitext(relative_path)[0]
                generated_module = f"{GENERATED_IMPORT_PREFIX}.{module_relative_path.replace(os.sep, '.')}"
                _write_compat_file(compat_path, _stub_wrapper_content(generated_module))


def generate_compat_packages() -> None:
    for package_root in COMPAT_PACKAGE_ROOTS:
        generate_compat_package(package_root)


def generate_pb(proto_file: str):
    proto_root = PROTO_INCLUDE_TONGTONG if _is_under(proto_file, PROTO_INCLUDE_TONGTONG) else PROTO_DIR
    relative_path = os.path.relpath(proto_file, proto_root)
    output_subdir = os.path.join(OUTPUT_DIR, os.path.dirname(relative_path))
    os.makedirs(output_subdir, exist_ok=True)

    include_paths = [proto_root, PROTO_DIR, PROTO_INCLUDE_ARENA, PROTO_INCLUDE_TONGTONG]
    include_paths = [p for p in dict.fromkeys(include_paths) if os.path.exists(p)]

    cmd = [
        sys.executable,
        "-m",
        "grpc_tools.protoc",
        *[f"-I{path}" for path in include_paths],
        f"--python_out={OUTPUT_DIR}",
        f"--pyi_out={OUTPUT_DIR}",
        f"--grpc_python_out={OUTPUT_DIR}",
        proto_file,
    ]
    print(f"[Info]  Compiling {proto_file}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.stdout:
        print(result.stdout.rstrip())
    if result.stderr:
        print(result.stderr.rstrip(), file=sys.stderr)
    if result.returncode != 0:
        sys.exit(result.returncode)

    # Generate __init__.py for all relevant directories
    base = os.path.splitext(os.path.relpath(proto_file, proto_root))[0]
    relevant_path = os.path.join(OUTPUT_DIR, base)
    ensure_init_packages(relevant_path)

def main():
    if not os.path.exists(PROTO_DIR):
        print(f"[Error] Proto directory not found: {PROTO_DIR}")
        sys.exit(1)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    ensure_arena_package()

    proto_files = list(find_proto_files())
    if not proto_files:
        print("[Warning]  No .proto files found.")
        return

    for proto_file in proto_files:
        generate_pb(proto_file)

    generate_compat_packages()

    print("[Info] gRPC Python code generation complete.")


if __name__ == "__main__":
    main()
