# Auto-generated by scripts/generate_pb2.py
"""Compatibility wrapper for arenaagent.generated.arena.agent.arena_agent_service_pb2_grpc."""

import importlib
import sys

_module = importlib.import_module("arenaagent.generated.arena.agent.arena_agent_service_pb2_grpc")
sys.modules[__name__] = _module
